import React, { useState } from 'react';
import {
  ShieldCheck,
  Bell,
  Plus,
  FileDown,
  Building2,
  Users,
  Key,
  ChevronDown,
  X,
  ExternalLink,
  Lock,
  Coins,
  Globe,
  Smartphone,
} from 'lucide-react';
import { useSecurity } from '../context/SecurityContext';
import { useCurrency } from '../context/CurrencyContext';
import { INITIAL_ORG, INITIAL_USERS, INITIAL_NOTIFICATIONS } from '../data/estateData';
import { UserRole, SystemNotification, SupportedCurrency } from '../types';

interface HeaderProps {
  onOpenQuickAction?: (actionType: 'property' | 'payment' | 'request' | 'invite' | 'momo') => void;
  onOpenSecurityModal?: () => void;
  notifications?: SystemNotification[];
  onMarkNotificationRead?: (id: string) => void;
  activeTab?: string;
}

export const Header: React.FC<HeaderProps> = ({
  onOpenQuickAction = () => {},
  onOpenSecurityModal = () => {},
  notifications = INITIAL_NOTIFICATIONS,
  onMarkNotificationRead = () => {},
}) => {
  const {
    currentUser,
    activeRole,
    setActiveRole,
    securityControls,
    showSecurityNotification,
    loginSession,
    lockSession,
    openMfaChallenge,
  } = useSecurity();
  const { activeCurrency, setActiveCurrency, currencies } = useCurrency();
  const [showRoleMenu, setShowRoleMenu] = useState(false);
  const [showNotifMenu, setShowNotifMenu] = useState(false);
  const [showQuickMenu, setShowQuickMenu] = useState(false);
  const [showCurrencyMenu, setShowCurrencyMenu] = useState(false);

  const unreadCount = notifications.filter((n) => n.unread).length;
  const activeControlsCount = securityControls.filter((c) => c.active).length;

  const handleExportReport = () => {
    showSecurityNotification('Generating HMAC-signed financial & occupancy audit report (PDF). Download initialized.');
    const blob = new Blob([
      `ESTATEFLOW AUDIT REPORT\nOrganization: ${INITIAL_ORG.name}\nDate: ${INITIAL_ORG.dateString}\nGenerated by: ${currentUser.name} (${currentUser.roleTitle})\nMonthly Revenue: $${INITIAL_ORG.portfolioSummary.monthlyRevenue.toLocaleString()}\nOccupancy: ${INITIAL_ORG.portfolioSummary.occupancyPercent}%\nOpen Work Orders: ${INITIAL_ORG.portfolioSummary.openMaintenance}\nStatus: Verified Least-Privilege Scope`
    ], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `EstateFlow-Audit-Report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <header className="sticky top-0 z-30 bg-[#FFFDF9] border-b border-[#EAE6DF] shadow-xs">
      {/* Top Organization and Status Bar */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Brand & Organization Info */}
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-lg bg-amber-700 flex items-center justify-center text-white font-bold text-base shadow-xs tracking-wider">
                EF
              </div>
              <div>
                <div className="flex items-center space-x-2">
                  <span className="font-bold text-lg tracking-tight text-stone-900">EstateFlow</span>
                  <span className="hidden sm:inline-block px-1.5 py-0.5 text-[10px] font-semibold tracking-wider uppercase bg-amber-100 text-amber-900 rounded">
                    Web Dashboard
                  </span>
                </div>
                <div className="text-xs text-stone-500 flex items-center space-x-1.5">
                  <span className="font-medium text-stone-700">{INITIAL_ORG.name}</span>
                  <span>•</span>
                  <span>{INITIAL_ORG.dateString}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Action Elements: Security Status, Notifications, Role Switcher, Quick Actions */}
          <div className="flex items-center space-x-2 sm:space-x-3">
            {/* Multi-Currency Selector Dropdown */}
            <div className="relative">
              <button
                id="header-currency-selector-btn"
                onClick={() => setShowCurrencyMenu(!showCurrencyMenu)}
                className="inline-flex items-center space-x-1.5 px-2.5 py-1.5 rounded-lg text-xs font-bold bg-amber-50/80 text-amber-950 border border-amber-300 hover:bg-amber-100/70 transition-all shadow-2xs"
                title="Select active display currency (USD, EUR, GBP, CFA)"
              >
                <span>{currencies[activeCurrency].flag}</span>
                <span className="font-mono">{activeCurrency}</span>
                <span className="text-stone-500 font-normal">({currencies[activeCurrency].symbol})</span>
                <ChevronDown className="w-3 h-3 text-stone-500 ml-0.5" />
              </button>

              {showCurrencyMenu && (
                <div className="absolute right-0 mt-2 w-64 bg-white rounded-xl shadow-xl border border-stone-200 py-2 z-50 animate-in fade-in">
                  <div className="px-3 py-1.5 border-b border-stone-100 flex items-center justify-between">
                    <div>
                      <span className="text-xs font-bold text-stone-900">Display Currency</span>
                      <p className="text-[10px] text-stone-500">Live conversion across all modules</p>
                    </div>
                    <button
                      onClick={() => setShowCurrencyMenu(false)}
                      className="text-stone-400 hover:text-stone-600"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <div className="p-1 space-y-1">
                    {(['USD', 'EUR', 'GBP', 'CFA'] as SupportedCurrency[]).map((cur) => {
                      const conf = currencies[cur];
                      const isSelected = activeCurrency === cur;
                      return (
                        <button
                          key={cur}
                          onClick={() => {
                            setActiveCurrency(cur);
                            setShowCurrencyMenu(false);
                            showSecurityNotification(`Switched platform currency to ${conf.name} (${conf.symbol}).`);
                          }}
                          className={`w-full text-left px-2.5 py-2 rounded-lg flex items-center justify-between transition-colors ${
                            isSelected
                              ? 'bg-amber-50 text-amber-950 font-bold border border-amber-200'
                              : 'hover:bg-stone-50 text-stone-700'
                          }`}
                        >
                          <div className="flex items-center space-x-2">
                            <span className="text-base">{conf.flag}</span>
                            <div>
                              <div className="text-xs leading-none">
                                {cur} <span className="font-mono font-bold text-stone-900">({conf.symbol})</span>
                              </div>
                              <div className="text-[10px] text-stone-500 mt-0.5">{conf.name}</div>
                            </div>
                          </div>
                          <div className="text-right">
                            <span className="text-[10px] font-mono text-stone-400">
                              {cur === 'USD' ? 'Base: 1.00' : `1$ = ${conf.rateAgainstUSD}`}
                            </span>
                          </div>
                        </button>
                      );
                    })}
                  </div>

                  <div className="px-3 pt-2 pb-1 border-t border-stone-100 text-[10px] text-stone-400 font-mono">
                    Router routes: EUR, USD, GBP, CFA
                  </div>
                </div>
              )}
            </div>

            {/* Security Status Indicator */}
            <button
              onClick={onOpenSecurityModal}
              id="header-security-badge"
              className="inline-flex items-center space-x-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium bg-emerald-50 text-emerald-800 border border-emerald-200 hover:bg-emerald-100 transition-colors"
              title="Click to view all 5 security controls"
            >
              <ShieldCheck className="w-4 h-4 text-emerald-600" />
              <span className="hidden md:inline font-mono font-semibold">{activeControlsCount}/5</span>
              <span className="hidden lg:inline">Security controls on</span>
            </button>

            {/* Notifications Popover Toggle */}
            <div className="relative">
              <button
                id="header-notifications-btn"
                onClick={() => setShowNotifMenu(!showNotifMenu)}
                className="relative p-2 text-stone-600 hover:text-stone-900 hover:bg-stone-100 rounded-lg transition-colors"
                aria-label="Notifications"
              >
                <Bell className="w-5 h-5" />
                {unreadCount > 0 && (
                  <span className="absolute top-1.5 right-1.5 w-4 h-4 bg-amber-600 text-white text-[10px] font-bold rounded-full flex items-center justify-center">
                    {unreadCount}
                  </span>
                )}
              </button>

              {showNotifMenu && (
                <div className="absolute right-0 mt-2 w-80 sm:w-96 bg-white rounded-xl shadow-xl border border-stone-200 py-2 z-50">
                  <div className="px-4 py-2 border-b border-stone-100 flex items-center justify-between">
                    <span className="font-semibold text-sm text-stone-900">Notifications ({unreadCount} new)</span>
                    <button
                      onClick={() => setShowNotifMenu(false)}
                      className="text-stone-400 hover:text-stone-600"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                  <div className="max-h-72 overflow-y-auto divide-y divide-stone-100">
                    {notifications.map((n) => (
                      <div
                        key={n.id}
                        onClick={() => onMarkNotificationRead(n.id)}
                        className={`px-4 py-3 hover:bg-stone-50 cursor-pointer transition-colors ${
                          n.unread ? 'bg-amber-50/50' : ''
                        }`}
                      >
                        <div className="flex items-start justify-between">
                          <p className="text-xs font-semibold text-stone-900">{n.title}</p>
                          <span className="text-[10px] text-stone-400 whitespace-nowrap">{n.timeAgo}</span>
                        </div>
                        <p className="text-xs text-stone-600 mt-1">{n.description}</p>
                        {n.unread && (
                          <div className="mt-1 flex items-center space-x-1">
                            <span className="w-1.5 h-1.5 rounded-full bg-amber-600 inline-block"></span>
                            <span className="text-[10px] font-medium text-amber-700">Click to acknowledge</span>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Export Report CTA */}
            <button
              onClick={handleExportReport}
              id="header-export-report-btn"
              className="hidden sm:inline-flex items-center space-x-1.5 px-3 py-1.5 text-xs font-medium text-stone-700 bg-white border border-stone-300 rounded-lg hover:bg-stone-50 transition-colors shadow-2xs"
            >
              <FileDown className="w-3.5 h-3.5 text-stone-500" />
              <span>Export report</span>
            </button>

            {/* Quick Action Dropdown */}
            <div className="relative">
              <button
                onClick={() => setShowQuickMenu(!showQuickMenu)}
                id="header-quick-action-btn"
                className="inline-flex items-center space-x-1 px-3 py-1.5 text-xs font-semibold text-white bg-amber-700 hover:bg-amber-800 rounded-lg transition-colors shadow-2xs"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Quick action</span>
                <ChevronDown className="w-3 h-3 ml-0.5 opacity-70" />
              </button>

              {showQuickMenu && (
                <div className="absolute right-0 mt-2 w-56 bg-white rounded-xl shadow-xl border border-stone-200 py-1.5 z-50">
                  <div className="px-3 py-1 text-[11px] font-semibold text-stone-400 uppercase tracking-wider">
                    Jump to
                  </div>
                  <button
                    onClick={() => {
                      setShowQuickMenu(false);
                      onOpenQuickAction('property');
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-stone-700 hover:bg-amber-50 hover:text-amber-900 flex items-center space-x-2"
                  >
                    <Building2 className="w-4 h-4 text-amber-700" />
                    <div>
                      <div className="font-medium">Add property</div>
                      <div className="text-[10px] text-stone-500">Register a building</div>
                    </div>
                  </button>
                  <button
                    onClick={() => {
                      setShowQuickMenu(false);
                      onOpenQuickAction('payment');
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-stone-700 hover:bg-amber-50 hover:text-amber-900 flex items-center space-x-2"
                  >
                    <Key className="w-4 h-4 text-emerald-600" />
                    <div>
                      <div className="font-medium">Log payment</div>
                      <div className="text-[10px] text-stone-500">Record rent received</div>
                    </div>
                  </button>
                  <button
                    onClick={() => {
                      setShowQuickMenu(false);
                      onOpenQuickAction('request');
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-stone-700 hover:bg-amber-50 hover:text-amber-900 flex items-center space-x-2"
                  >
                    <Plus className="w-4 h-4 text-amber-600" />
                    <div>
                      <div className="font-medium">New request</div>
                      <div className="text-[10px] text-stone-500">Open work order</div>
                    </div>
                  </button>
                  <button
                    onClick={() => {
                      setShowQuickMenu(false);
                      onOpenQuickAction('invite');
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-stone-700 hover:bg-amber-50 hover:text-amber-900 flex items-center space-x-2"
                  >
                    <Users className="w-4 h-4 text-blue-600" />
                    <div>
                      <div className="font-medium">Invite tenant / staff</div>
                      <div className="text-[10px] text-stone-500">Send portal access</div>
                    </div>
                  </button>

                  <button
                    onClick={() => {
                      setShowQuickMenu(false);
                      onOpenQuickAction('momo');
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-amber-950 hover:bg-amber-100/70 bg-amber-50/60 flex items-center space-x-2 border-t border-amber-100"
                  >
                    <Smartphone className="w-4 h-4 text-amber-700" />
                    <div>
                      <div className="font-bold flex items-center space-x-1">
                        <span>Mobile Money</span>
                        <span className="text-[9px] bg-yellow-400 text-stone-900 px-1 rounded font-bold">MoMo/OM</span>
                      </div>
                      <div className="text-[10px] text-stone-500">Collect via MTN & Orange</div>
                    </div>
                  </button>
                </div>
              )}
            </div>

            {/* Multi-Factor Authentication (MFA) Status Badge */}
            <button
              type="button"
              onClick={() =>
                openMfaChallenge({
                  purpose: 'login',
                  channel: currentUser.mfaPreferredChannel || 'phone',
                  user: currentUser,
                })
              }
              className="hidden sm:inline-flex items-center space-x-1.5 px-2.5 py-1.5 rounded-lg text-xs font-bold bg-emerald-50 text-emerald-900 border border-emerald-300 hover:bg-emerald-100 transition-colors shadow-2xs cursor-pointer"
              title={`MFA Protection Active (${loginSession.verifiedChannel === 'phone' ? 'Phone SMS' : 'Email'}). Click to challenge or verify.`}
            >
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-700" />
              <span className="font-mono text-[11px]">
                MFA: {loginSession.verifiedChannel === 'phone' ? 'Phone SMS' : 'Email'}
              </span>
            </button>

            {/* Role & Persona Switcher (RBAC Simulator) */}
            <div className="relative">
              <button
                onClick={() => setShowRoleMenu(!showRoleMenu)}
                id="header-role-switcher-btn"
                className="flex items-center space-x-2 pl-2 pr-2.5 py-1 text-xs rounded-lg border border-stone-200 hover:border-stone-300 bg-stone-50 transition-colors"
                title="Change active role to test RBAC least-privilege security"
              >
                <div className={`w-6 h-6 rounded-full flex items-center justify-center text-white text-[11px] font-bold ${currentUser.avatarColor}`}>
                  {currentUser.name.charAt(0)}
                </div>
                <div className="hidden sm:block text-left">
                  <div className="font-semibold text-stone-900 leading-tight truncate max-w-[120px]">
                    {currentUser.name}
                  </div>
                  <div className="text-[10px] text-amber-800 font-mono font-medium leading-none">
                    {currentUser.role}
                  </div>
                </div>
                <ChevronDown className="w-3.5 h-3.5 text-stone-400" />
              </button>

              {showRoleMenu && (
                <div className="absolute right-0 mt-2 w-72 bg-white rounded-xl shadow-xl border border-stone-200 py-2 z-50">
                  <div className="px-3 py-1.5 border-b border-stone-100">
                    <p className="text-xs font-bold text-stone-900">Least-Privilege RBAC Role</p>
                    <p className="text-[11px] text-stone-500">Switch role to test access boundaries across all 8 modules:</p>
                  </div>
                  <div className="divide-y divide-stone-100 max-h-72 overflow-y-auto">
                    {INITIAL_USERS.map((user) => (
                      <button
                        key={user.id}
                        onClick={() => {
                          setActiveRole(user.role);
                          setShowRoleMenu(false);
                        }}
                        className={`w-full text-left px-3 py-2 text-xs flex items-start space-x-2.5 hover:bg-stone-50 transition-colors ${
                          user.role === activeRole ? 'bg-amber-50/70 border-l-2 border-amber-600' : ''
                        }`}
                      >
                        <div className={`w-7 h-7 rounded-full flex-shrink-0 flex items-center justify-center text-white text-xs font-bold ${user.avatarColor}`}>
                          {user.name.charAt(0)}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between">
                            <span className="font-semibold text-stone-900 truncate">{user.name}</span>
                            <span className="text-[10px] font-mono px-1 rounded bg-stone-100 text-stone-600">{user.role}</span>
                          </div>
                          <p className="text-[11px] text-stone-500 truncate">{user.roleScope}</p>
                          <div className="text-[10px] text-emerald-700 mt-0.5">
                            MFA: {user.mfa} · {user.mfaPreferredChannel === 'phone' ? 'Phone SMS' : 'Email'}
                          </div>
                        </div>
                      </button>
                    ))}
                  </div>

                  {/* Lock Screen & MFA Trigger Actions */}
                  <div className="p-2 border-t border-stone-100 bg-stone-50/60 flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => {
                        setShowRoleMenu(false);
                        openMfaChallenge({
                          purpose: 'login',
                          channel: currentUser.mfaPreferredChannel || 'phone',
                          user: currentUser,
                        });
                      }}
                      className="flex-1 py-1 px-2 rounded-lg bg-white border border-stone-200 hover:bg-stone-50 text-stone-700 text-[11px] font-bold flex items-center justify-center space-x-1 transition-colors cursor-pointer"
                      title="Challenge account identity with 6-digit MFA OTP code"
                    >
                      <ShieldCheck className="w-3.5 h-3.5 text-amber-700" />
                      <span>Test Login MFA</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => {
                        setShowRoleMenu(false);
                        lockSession();
                      }}
                      className="py-1 px-2.5 rounded-lg bg-stone-900 hover:bg-stone-800 text-white text-[11px] font-bold flex items-center space-x-1 transition-colors cursor-pointer"
                      title="Engage zero-trust workstation lock"
                    >
                      <Lock className="w-3.5 h-3.5 text-amber-400" />
                      <span>Lock</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};
